### ISSUE TITLE
Error on occ preview:pre-generate

### ISSUE THREAD

**Issue by jkolo** [rullzer/previewgenerator#4] opened 2016-12-14 08:22 UTC
`occ preview:pre-generate` command generates an exception: 
```
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/kolosowscy.cloud/htdocs/lib/private/Files/Filesystem.php:719
Stack trace:
#0 /var/www/kolosowscy.cloud/htdocs/lib/private/legacy/image.php(597): OC\Files\Filesystem::file_get_contents('/var/www/koloso...')
#1 /var/www/kolosowscy.cloud/htdocs/lib/private/Preview/MP3.php(80): OC_Image->loadFromFile('/var/www/koloso...')
#2 /var/www/kolosowscy.cloud/htdocs/lib/private/Preview/MP3.php(64): OC\Preview\MP3->getNoCoverThumbnail()
#3 /var/www/kolosowscy.cloud/htdocs/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\MP3->getThumbnail('/files/Dokument...', 2048, 2048, false, Object(OC\Files\View))
#4 /var/www/kolosowscy.cloud/htdocs/lib/private/Preview/Generator.php(155): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\MP3), Object(OC\Files\Node\File), 2048, 2048)
#5 /var/www/kolosowscy.cloud/htdocs/lib/private/Preview/Generator.php(108): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'audio/mpeg')
#6 /var/www/kolosowscy.cloud/htdocs/lib/private/PreviewManager.php(182): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'audio/mpeg')
#7 /var/www/kolosowscy.cloud/htdocs/apps/previewgenerator/lib/Command/PreGenerate.php(158): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#8 /var/www/kolosowscy.cloud/htdocs/apps/previewgenerator/lib/Command/PreGenerate.php(181): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#9 /var/www/kolosowscy.cloud/htdocs/apps/previewgenerator/lib/Command/PreGenerate.php(183): OCA\PreviewGenerator\Command\PreGenerate->processFolder(Object(OC\Files\Node\Folder))
#10 /var/www/kolosowscy.cloud/htdocs/apps/previewgenerator/lib/Command/PreGenerate.php(150): OCA\PreviewGenerator\Command\PreGenerate->processFolder(Object(OC\Files\Node\Folder))
#11 /var/www/kolosowscy.cloud/htdocs/apps/previewgenerator/lib/Command/PreGenerate.php(113): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#12 /var/www/kolosowscy.cloud/htdocs/apps/previewgenerator/lib/Command/PreGenerate.php(91): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#13 /var/www/kolosowscy.cloud/htdocs/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/kolosowscy.cloud/htdocs/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/kolosowscy.cloud/htdocs/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/kolosowscy.cloud/htdocs/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/kolosowscy.cloud/htdocs/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/kolosowscy.cloud/htdocs/console.php(90): OC\Console\Application->run()
#19 /var/www/kolosowscy.cloud/htdocs/occ(11): require_once('/var/www/koloso...')
#20 {main}
```

**Comment by jiml8** [comment] 2017-01-03 03:03
I am seeing this also.

**Comment by hoellen** [comment] 2017-01-05 07:07
Same here. If you need more information please let me know.

**Comment by rullzer** [comment] 2017-03-08 15:34
I think this is caused by a bad image file. Altough I'm not sure as I've not been able to reproduce this on my dev instance at all.

Anyway https://github.com/rullzer/previewgenerator/pull/31 should mitigate the issue. It will still fail on that file. But now only once as the file will be skipped in the next run.

**Comment by rullzer** [comment] 2017-03-14 20:40
This was a server bug and will be fixed in NC 12. (https://github.com/nextcloud/server/pull/3794)

**Closed by rullzer** 2017-03-14 20:40 UTC
