### ISSUE TITLE
Preview Generator 1.0.1 → crash on mp3 file without cover image

### ISSUE THREAD

**Issue by Sanookmakmak** [rullzer/previewgenerator#22] opened 2017-02-06 08:54 UTC
The app stops working in case of mp3 without a cover image.

No way to debug it because the filename is truncated in nextcloud.log (see [#19](https://github.com/rullzer/previewgenerator/issues/19))

More info:
https://help.nextcloud.com/t/preview-generate-all-not-working/8190

**Comment by xraMsamohT** [comment] 2017-02-06 16:39
```
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /home/www/xxxxxxxx/lib/private/Files/Filesystem.php:719
Stack trace:
#0 /home/www/xxxxxxxx/lib/private/legacy/image.php(597): OC\Files\Filesystem::file_get_contents('/home/www/xxxxx...')
#1 /home/www/xxxxxxxx/lib/private/Preview/MP3.php(80): OC_Image->loadFromFile('/home/www/xxxxx...')
#2 /home/www/xxxxxxxx/lib/private/Preview/MP3.php(64): OC\Preview\MP3->getNoCoverThumbnail()
#3 /home/www/xxxxxxxx/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\MP3->getThumbnail('/files/xxxxxxxx...', 2048, 2048, false, Object(OC\Files\View))
#4 /home/www/xxxxxxxx/lib/private/Preview/Generator.php(155): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\MP3), Object(OC\Files\Node\File), 2048, 2048)
#5 /home/www/xxxxxxxx/lib/private/Preview/Generator.php(108): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'audio/mpeg')
#6 /home/www/xxxxxxxx/lib/private/PreviewManager.php(182): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'audio/mpeg')
#7 /home/www/xxxxxxxx/apps2/previewgenerator/lib/Command/PreGenerate.php(158): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#8 /home/www/xxxxxxxx/apps2/previewgenerator/lib/Command/PreGenerate.php(181): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#9 /home/www/xxxxxxxx/apps2/previewgenerator/lib/Command/PreGenerate.php(183): OCA\PreviewGenerator\Command\PreGenerate->processFolder(Object(OC\Files\Node\Folder))
#10 /home/www/xxxxxxxx/apps2/previewgenerator/lib/Command/PreGenerate.php(150): OCA\PreviewGenerator\Command\PreGenerate->processFolder(Object(OC\Files\Node\Folder))
#11 /home/www/xxxxxxxx/apps2/previewgenerator/lib/Command/PreGenerate.php(113): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#12 /home/www/xxxxxxxx/apps2/previewgenerator/lib/Command/PreGenerate.php(91): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#13 /home/www/xxxxxxxx/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/www/xxxxxxxx/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/www/xxxxxxxx/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/www/xxxxxxxx/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/www/xxxxxxxx/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/www/xxxxxxxx/console.php(90): OC\Console\Application->run()
#19 /home/www/xxxxxxxx/occ(11): require_once('/home/www/xxxxx...')
#20 {main}
```

**Comment by rullzer** [comment] 2017-02-07 07:30
Basically caused by https://github.com/nextcloud/server/issues/2739

Has to be fixed in the server.

**Closed by rullzer** 2017-02-07 07:30 UTC
